In [1]:
import numpy as np

In [2]:
weather = np.array([[0.6,0.4,0.3],[0.3,0.4,0.3],[0.1,0.2,0.4]])
weather

array([[ 0.6,  0.4,  0.3],
       [ 0.3,  0.4,  0.3],
       [ 0.1,  0.2,  0.4]])

In [12]:
snowy = np.array([0.2,0.8,0])

In [13]:
y_2 = np.matmul(weather,snowy)
y_2

array([ 0.44,  0.38,  0.18])

In [14]:
y_3 = np.matmul(weather,y_2)
y_3

array([ 0.47 ,  0.338,  0.192])

In [6]:
def repeated_matmul(transition_matrix,step_number,state_vector):
    print(np.matmul(np.linalg.matrix_power(transition_matrix,step_number-1),state_vector))

In [15]:
repeated_matmul(weather,1,snowy)

[ 0.2  0.8  0. ]


In [16]:
repeated_matmul(weather,2,snowy)

[ 0.44  0.38  0.18]


In [17]:
repeated_matmul(weather,5,snowy)

[ 0.47582  0.33338  0.1908 ]


In [18]:
repeated_matmul(weather,50,snowy)

[ 0.47619048  0.33333333  0.19047619]


In [19]:
repeated_matmul(weather,10000,snowy)

[ 0.47619048  0.33333333  0.19047619]
