In [2]:
import numpy as np

In [5]:
A= np.array([[2,3],[4,9]])
B = np.array([[-2,-6],[5,15]])
C = np.array([[7,1,4],[-1,0,4]])
D = np.array([[1],[-1]])

In [6]:
A+B

array([[ 0, -3],
       [ 9, 24]])

In [9]:
A-B

array([[ 4,  9],
       [-1, -6]])

In [10]:
B+D

array([[-1, -5],
       [ 4, 14]])

In [12]:
np.matmul(A,B)

array([[ 11,  33],
       [ 37, 111]])

In [13]:
np.matmul(B,A)

array([[-28, -60],
       [ 70, 150]])

In [14]:
np.matmul(D,A)

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [15]:
np.matmul(A,D)

array([[-1],
       [-5]])

In [16]:
np.linalg.inv(A)

array([[ 1.5       , -0.5       ],
       [-0.66666667,  0.33333333]])

In [17]:
C.transpose()

array([[ 7, -1],
       [ 1,  0],
       [ 4,  4]])

In [18]:
(3*D).transpose()

array([[ 3, -3]])

In [19]:
3*(D.transpose())

array([[ 3, -3]])

In [20]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [21]:
np.linalg.det(A)

6.0

In [23]:
q1=np.linalg.inv(A)

In [24]:
np.matmul(A,q1)

array([[  1.00000000e+00,   1.11022302e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [25]:
np.matmul(q1,A)

array([[  1.00000000e+00,   8.88178420e-16],
       [  0.00000000e+00,   1.00000000e+00]])

In [26]:
np.linalg.det(B)

-1.6653345369377366e-15